### ISSUE TITLE
Question: How to change the 400 error response object?

### ISSUE THREAD

**Issue by gtbono** [anatine/zod-plugins#106]
Hello!

I am using nestjs-zod to validate the request body object, when I sent an invalid request it comes back as a 400 response with this object:

```
{
    "statusCode": 400,
    "message": [
        "age: Expected number, received string"
    ],
    "error": "Bad Request"
}
```

but I want it in another format, something like:

```
{
    "statusCode": 400,
    "message": [
        { "age": "Expected date, received string" }
    ],
    "error": "Bad Request"
}
```

Is there any way to customize this? thanks :)

**Comment by Brian-McBride** [comment]
I am going to guess that this is an aspect of NestJS. 
This plugin is crazy simple, it really is just a validation pipe. 
Look for NestJS docs around changing response errors in a validation pipe and I bet you'll find your answer there.
