### ISSUE TITLE
zod-mock: Does not properly handle `ZodRecord` type

### ISSUE THREAD

**Issue by hannah-bulmer** [anatine/zod-plugins#107]
The `ZodRecord` type is handled with the same `parseObject` method that is used for `ZodObject`, but throws an error because `ZodRecord` does not have a `shape` property like an object - it instead contains a `keyType` and a `valueType` at the `_def` level. Therefore the code

```js
const schema =  z.record(z.string())

generateMock(schema)
```

throws an unexpected error. This should be pretty easy to fix by correctly handling the `ZodRecord` case.

**Comment by Brian-McBride** [comment]
I don't have the time to look into this now. a PR fix would be great if you have an idea there. 
Otherwise I'll get something in place next week.
