### ISSUE TITLE
[zod-mock] Is it possible to add generators for custom types?

### ISSUE THREAD

**Issue by acron0** [anatine/zod-plugins#109]
Here is an example schema
```typescript
const FooType = z.object({
        myDate: z.custom<Date>((value: unknown): Date => {
            return new Date(value as string)
        }),
        myString: z.string(),
    })
```

As expected, `generateMock` produces an `undefined` value for `myDate`:

```typescript
generateMock(FooType)
=>  { myDate: undefined, myString: 'dolore' }
```

How is it possible for me to define a generator for `myDate`?

`stringMap` doesn't seem to trigger, and `backupMocks` works with `ZodAny` but I don't know what type I _should_ use.
```typescript
generateMock(FooType, { stringMap: { myDate: () => new Date().toISOString() } })
=> { myDate: undefined, myString: 'consequuntur' }
```

**Comment by iamchanii** [comment]
https://github.com/anatine/zod-plugins/blob/0c52ae1eef460ff6403b09b08bcdd0b404c0c965/packages/zod-mock/src/lib/zod-mock.ts#L580-L583

If a generator that from `backupMocks` takes two arguments; `zodRef` and `options`,  it seems to support custom type enough.

(Disclaimer: I'm not used to this codebase)

```ts
const generator = options.backupMocks[typeName];
if (generator) {
  return generator(zodRef as never, options);
}

const mockData = generateMock(schema, {
  backupMocks: {
    ZodCustom: (_ref, options) => { /* ... */ }
  }
});
```

**Comment by iamchanii** [comment]
I just opened a pull request. If you are still interested in this issue, you can review or comment it.

PR: #114 

The changes and test cases related to this are here:

https://github.com/anatine/zod-plugins/pull/114/files#diff-e7250a39ead9d6eaccda1eaa352c2c0e57aaeb7530eeeed176f8eebf441c26e0R370-R395
