### ISSUE TITLE
[zod-nestjs] Add NestJS 10.0 to peerDependencies

### ISSUE THREAD

**Issue by BitYoungjae** [anatine/zod-plugins#135]
Every time I install the package, I get a warning because NestJS 10.0 is not included in the peerDependencies. 
Could you possibly add version 10 as well?

**Comment by Brian-McBride** [comment]
Sorry, I have been slammed. I need a co-maintainer. 
Yes, I'll do that now.

**Comment by Brian-McBride** [comment]
This should be solved in a clear major release
https://www.npmjs.com/package/@anatine/zod-nestjs
