### ISSUE TITLE
[zod-openapi] Null handling in NestJS

### ISSUE THREAD

**Issue by erkstruwe** [anatine/zod-plugins#181]
Hi there and thanks for your awesome library!

#179  changed `null` handling from OpenAPI 3.0 to OpenAPI 3.1 syntax (from `nullable: true` to `type: [..., "null"]`.

According to OpenAPI 3.0 documentation at https://swagger.io/docs/specification/data-models/data-types/, the syntax now used is explicitly marked as "incorrect". Thus, schemas created in NestJS using `zod-openapi` and `zod-nestjs` (which uses OpenAPI 3.0) are no longer working with downstream tools such as `openapi-generator` (e. g. with `typescript-axios`).

How can we get nullable attributes to work again?

**Comment by MatthieuJnon** [comment]
We are having the same issue over here, this is a breaking change.

**Comment by Brian-McBride** [comment]
So, what do we do? Maintain two versions for each version of OpenAPI?

I'm completely open to suggestions. It sounds like NestJS isn't going to update their OpenAPI Spec anytime soon. 

Maybe we create an option to specify what API spec you want to use and generate to that one?

**Comment by erkstruwe** [comment]
NestJS's `@nestjs/swagger` uses a hardcoded OpenAPI version 3.0 [here](https://github.com/nestjs/swagger/blob/ed528d44d416f78a8159995de31b9d4df6024762/lib/swagger-module.ts#L43).

Given the progress this library has made towards OpenAPI 3.1, I can imagine it makes sense to keep types according to OpenAPI 3.1 throughout the `zod-openapi` package (e. g. `extendApi` parameters) and to manually change this "back" to OpenAPI 3.0 in `zod-nestjs`. After all, the [list of changes](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) is rather brief.

From my point of view, [SchemaHolderClass._OPENAPI_METADATA_FACTORY()](https://github.com/anatine/zod-plugins/blob/1cfb5efb37d4d299373b89b084dac2594613bd23/packages/zod-nestjs/src/lib/create-zod-dto.ts#L68) would be a good place to pull that off by altering the `generatedSchema`.

Alternatively, we could add a version parameter to `zod-openapi`s `generateSchema` function and handle the differences there. However, this could make typing more difficult (e. g. how should ).

**Comment by erkstruwe** [comment]
@Brian-McBride I drafted a PR for the "nullable" and "exclusive limits" issues. Could you please let me know what you think about it? Thanks!

**Comment by Tirke** [comment]
@erkstruwe how do we opt-in into that if I don't explicitly pin `@anatine/zod-openapi` to `2.2.1` I still have the issue.
