### ISSUE TITLE
[zod-mock] stringMap not applied to objects in arrays

### ISSUE THREAD

**Issue by madi-tracksuit** [anatine/zod-plugins#183]
I'm trying to use the `stringMap` to override the mocks for date strings throughout my schema. It works most of the time, but seems to fail when the string in question is in an array of objects. 

Example pseudocode:

```js
const schema = z.object({
  data: z.object({
    startDate: z.string()
   }).array().optional()
})

const mock = generateMock(schema, { 
  stringMap: {
    startDate: customDate
  }
})

// mock = { data: [ { startDate: lorem } ] }
```

**Comment by ckstn0777** [comment]
@madi-tracksuit Have you resolved it?
