### ISSUE TITLE
[zod-openapi] TSConfig difference produces different results

### ISSUE THREAD

**Issue by oof2win2** [anatine/zod-plugins#21]
So i'm trying to use `@anatine/zod-openapi` in conjunction with zod to create openapi3 schemas. I have this code, but running it on different tsconfigs literally outputs different results which IMO is a pretty big issue. with `module` set to `commonjs` and `"type": "commonjs"` in package.json, it works fine and gives the expected result. When `module` is however set to `es2020` and `"type": "module"`, it produces the wrong result.

```ts
import { generateSchema } from "@anatine/zod-openapi"
import { z } from "zod"

const testSchema = z.object({
    shortdesc: z.string(),
    longdesc: z.string()
})

console.log(generateSchema(testSchema))

// expects below
{
  type: 'object',
  properties: { shortdesc: { type: 'string' }, longdesc: { type: 'string' } },
  required: [ 'shortdesc', 'longdesc' ],
}

// wrong result
{
  type: 'object',
  properties: { shortdesc: { type: 'string' }, longdesc: { type: 'string' } },
  required: [ 'shortdesc', 'longdesc' ],
  additionalProperties: { readOnly: true }
}
```

**Comment by Brian-McBride** [comment]
Can you help chase this down? Is it a difference in Zod? 

It looks read only is set to true when it discovers a z.never()

https://github.com/anatine/zod-plugins/blob/bc6766db2ff5209b61452fc8edb7fa0e9162a877/libs/zod-openapi/src/lib/zod-openapi.ts#L332-L334

And this is the conditional statement
https://github.com/anatine/zod-plugins/blob/bc6766db2ff5209b61452fc8edb7fa0e9162a877/libs/zod-openapi/src/lib/zod-openapi.ts#L385-L395

It uses the zod types defined in the zod metadata to match what function runs with what type.

**Comment by oof2win2** [comment]
Yeah, sure. I don't know what you are asking though. Do you want me to log which functions are being executed in the conditional statement?

**Comment by Brian-McBride** [comment]
Maybe you can create an example repo with the problem. I'm happy to trace it down - my time is a bit compressed this week and the main repo is testing properly. 

The fact that it is esmodule related is a bit confusing. That shouldn't change the code. But it does change how the the imports work. The `zod-openapi` is so simple, I suspect it is probably an issue with the Zod distribution and the fix will have to come from there. In the meantime, we might be able to create a proper detection and catch that error.

**Comment by oof2win2** [comment]
See this repo & branch https://github.com/oof2win2/bug-repro/tree/anatine/zod-plugins/zod-openapi for the minimal config

**Comment by Brian-McBride** [comment]
Thanks. 
I'm PST timezone, so it will be about 6 to 8 hours till I can get to the solution. But this should make it super fast to solve.

**Comment by Brian-McBride** [comment]
Ok. What we are seeing is an issue with `zod` and the compiled esm module. 

If you look into the `node_modules/zod` you'll see `index.js` and `index.mjs`. There we find that the second file has been uglified. Unfortunately, this is breaking the class names. 

#### Common JS
```
ZodObject {
  spa: [Function (anonymous)],
  superRefine: [Function (anonymous)],
  _def: {
    shape: [Function: shape],
    unknownKeys: 'strip',
    catchall: ZodNever {
      spa: [Function (anonymous)],
      superRefine: [Function (anonymous)],
      _def: { typeName: 'ZodNever' },
      transform: [Function: bound ],
      default: [Function: bound ]
    },
    typeName: 'ZodObject'
  },
  transform: [Function: bound ],
  default: [Function: bound ],
  _cached: null,
  nonstrict: [Function (anonymous)],
  augment: [Function (anonymous)],
  extend: [Function (anonymous)]
}
```

#### esmodules
```
s {
  spa: [Function (anonymous)],
  superRefine: [Function (anonymous)],
  _def: {
    shape: [Function: shape],
    unknownKeys: 'strip',
    catchall: t {
      spa: [Function (anonymous)],
      superRefine: [Function (anonymous)],
      _def: { typeName: 'ZodNever' },
      transform: [Function: bound ],
      default: [Function: bound ]
    },
    typeName: 'ZodObject'
  },
  transform: [Function: bound ],
  default: [Function: bound ],
  _cached: null,
  nonstrict: [Function (anonymous)],
  augment: [Function (anonymous)],
  extend: [Function (anonymous)]
}
```

It is subtle, but we see the logging output of the class name `ZodObject` is being obfuscated into `s`. Others, like `ZodNever` are being converted to `t`.

I put an additional code check to look for another area of the Zod object structure to find the type of the object. This does seem to fix the issue. Ideally, though, the zod repo should not obfuscate the class names in the `.mjs` files. 

You should be good to go pulling down the new version.

**Comment by Brian-McBride** [comment]
While we have a fix, I did open a ticket in the [zod](https://github.com/colinhacks/zod) repo:

https://github.com/colinhacks/zod/issues/844

**Comment by oof2win2** [comment]
Thanks for the fix! Didn't even think that it could be there.
