### ISSUE TITLE
webpack unable to resolve index.js (becouse it doesn't exist)

### ISSUE THREAD

**Issue by henrikq** [anatine/zod-plugins#26]
Webpack produces the following error
```
Module not found: Error: Can't resolve '@anatine/zod-mock' in '/home/henrik/proj/prevent-ui/src/hooks/api'
resolve '@anatine/zod-mock' in '/home/henrik/proj/prevent-ui/src/hooks/api'
```

which makes sense, since it cant find `index.js` as specified by the package.json.

![image](https://user-images.githubusercontent.com/13659903/151368440-ddf805fe-74f9-4628-8edb-96832773638d.png)

Version: 2.0.0

when downgrading to 1.3.0, it workes fine.

**Comment by Brian-McBride** [comment]
Thanks. 
No idea why that is happening. I'll get that resolved immediately though

**Comment by Brian-McBride** [comment]
@henrikq It should be all good now. `2.0.2` is up. Thanks for the quick catch.
