### ISSUE TITLE
Support Discriminated unions

### ISSUE THREAD

**Issue by buresmi7** [anatine/zod-plugins#38]
Since Zod version [3.12.0](https://github.com/colinhacks/zod/releases/tag/v3.12.0) we can use `z.discriminatedUnion()`.

OpenApi target format is described here: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by Brian-McBride** [comment]
PR Merged #39

**Comment by stefanmo** [comment]
I need to use discriminated unions in my application but I can't get typescript to not cry about `createZodDto` when passing a z.discrimatedUnion object.

```typescript
const schema = z.discriminatedUnion("type", [firstSchema, otherSchema]) // both schemas have the type property

class Dto extends createZodDto(extendApi(schema)) {}

TS2509: Base constructor return type '{ type: "brick"; ... | { ...' is not an object type or intersection of object types with statically known members.
```

If I set typescript to ignore the errors then the code compiles and swagger shows the schema correctly.

Am I missing something?

**Comment by Brian-McBride** [comment]
@buresmi7  Do you have any thoughts on this? I haven't used `discriminatedUnion`, but your PR passes the test. 

@stefanmo Maybe put together some example test schemas so that we can run through the code and see what is going on there?

**Comment by buresmi7** [comment]
@Brian-McBride I prepared PR with test, but I am using only `zod-openapi`, so I do not know about `zod-nestjs`

**Comment by stefanmo** [comment]
I've created an example [in this repo](https://github.com/stefanmo/zod-nestjs) and when starting dev server it errors
```
src/schema.ts:26:29 - error TS2509: Base constructor return type '{ name?: string; age?: number; breed?: string; color?: "red"; } | { name?: string; age?: number; breed?: string; color?: "blue"; }' is not an object type or intersection of object types with statically known members.

26 export class CatDto extends createZodDto(CatZ) {}
```
