### ISSUE TITLE
NestJS createDTO to allow access moduleref

### ISSUE THREAD

**Issue by jonyeezs** [anatine/zod-plugins#41]
There are situations where validation needs to be done against a database or an API.

Zod provides Async parsing for these scenarios.

NestJS relies heavily on its DI module to retrieve provider instances.

More often the IO we need to access are within NestJS IOC.

In would help if we could get access to the IOC to create schema.

Idea:

```typescript
const dto = (inj: ModuleRef) => z.string().refine(async (v)  => inj.get(Service).check(v));

Export DTO extends CreateZodDto(dto)

ValidatorPipe() {
      transform() {
         schema  = metatype typeof function ? Schema(this.moduleRef) : Schema
      }
}
```

**Comment by Brian-McBride** [comment]
Myself, I often use `zod` to validate my data from my DB in the services I write. I'm not one for layering on ORMs. I like to keep my services somewhat portable so that I can use them in different frameworks without huge refactoring. 

So I might have something like 
```typescript
const fetchedDoc = someDatabaseCall()
const doc = await myZodSchema.parseAsync(fetchedDoc)
  .catch(err => { throw new Error('Internal Server Error : Bad Data') })
```

That's overly simplified, and I am not sure if this is what you are getting at?

**Comment by jonyeezs** [comment]
> Myself, I often use `zod` to validate my data from my DB in the services I write. I'm not one for layering on ORMs.

Yeah so this is more of validating incoming request against a DB/service.

> I'm not one for layering on ORMs

Likewise. But seeing this is a NestJS related library - not purely Zod, I reckon it isn't far fetch to layer NestJS' injector (ie ModuleRef) into zod.

I can get a PR going 👍

**Comment by Rayyan98** [comment]
@jonyeezs are we still getting that PR going ?

**Comment by jonyeezs** [comment]
Hi sorry for the long silence. I'm still evaluating if this is the best way of approaching the problem. I do want to inject something externally....maybe not the moduleRef. And could be out of bounds for this package. I'm happy to close this for now.
