### ISSUE TITLE
Parsing Native Enum return undefined

### ISSUE THREAD

**Issue by tifanrepo** [anatine/zod-plugins#48]
When parsing native enums that use strings, the parsing function return undefined.

For example:
 
enum Fruits {
APPLE = "APPLE"
}

Parsing enums like this fails. I suggest this fix: 

```
function parseNativeEnum(zodRef) {
	const { values } = zodRef._def
	const pick = Math.floor(Math.random() * (Object.values(values).length / 2))
	const key = Array.from(Object.keys(values))[pick]
	return values[values[key]]
}
```

This method access the values object using a key instead of a number.

**Comment by tifanrepo** [comment]
#50 Created pull request with fix

**Comment by Brian-McBride** [comment]
Thanks for the fix. 
I'm still having some weirdness with the github actions in this monorepo, so the release might have jumped a few patch numbers. 
3.5.5 should have your fix in it though.

**Comment by JeongJuhyeon** [comment]
Could this patch also be applied to zod-openapi, and thereby zod-nestjs?
