### ISSUE TITLE
@Query and @Param doesn't work with zod-nestjs

### ISSUE THREAD

**Issue by rgonzlz** [anatine/zod-plugins#5]
Hi!

I'm using @zod-nestjs with @Body and works fine, but with @Query and @Param doestn't appear in Swagger schemas.

I created a repo with the code: https://github.com/rgonzlz/zod-nestjs

**Comment by Brian-McBride** [comment]
I'm currently deep into a GraphQL project and I don't have time to track this down. 
Zod changed some data on his _def object that broke things. Maybe that is related. 

Unfortunately, this is using a very weird patching of the swagger module. 
I'm going to guess it is here:
https://github.com/anatine/zod-plugins/blob/main/libs/zod-nestjs/src/lib/patch-nest-swagger.ts

**Comment by alichampion** [comment]
@Brian-McBride just a nudge on this one!

**Comment by iSeiryu** [comment]
The link is https://github.com/anatine/zod-plugins/blob/main/packages/zod-nestjs/src/lib/patch-nest-swagger.ts now. The links keep changing from `packages` to `libs` and back on weekly basis...I keep getting 404 while trying to follow links in Readme and issues.

This adds the definition to Swagger (OpenApi spec)
```typescript
//books.controller.ts

@Controller('books')
export class BooksController {
  @Post()
  addBook(@Body() request: AddBookRequest): Book {
    return new Book(request.Title);
  }
}


// AddBookRequest.ts

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';

const AddBookRequestSchema = z.object({
  id: z.number(),
  title: z.string(),
  published: z.date(),
  completed: z.boolean(),
});

export class AddBookRequest extends createZodDto(AddBookRequestSchema) {}
```

But this does not
```typescript
//books.controller.ts

@Controller('books')
export class BooksController {
  @Get()
  addBook(@Query() query: GetBookQuery): Book {
    return new Book(query.Id);
  }
}


// GetBookQuery.ts

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';

const GetBookQuerySchema = z.object({
  id: z.number(),
  title: z.string()
});

export class GetBookQuery extends createZodDto(GetBookQuerySchema) {}
```

**Comment by Brian-McBride** [comment]
Function added via PRs #62 and #63
