### ISSUE TITLE
zod-mock: Option to throw errors when a zod type is not supported

### ISSUE THREAD

**Issue by josh-degraw** [anatine/zod-plugins#58]
I recently PR'd support for a few types that were missing, but it took me a while to figure out that it was because `zod-mock` was just returning `undefined` for types that were required by my zod schema.

I would have found this out earlier if it threw an error instead of returning undefined. I recognize it would be a breaking change to make that be the default behavior (although I personally think it would make sense to be the default behavior), so I would propose adding a flag to `GenerateMockOptions` to specify to throw an exception if a type is specified on the schema but not configured.

I'd be happy to throw up a PR for this, but I figured I'd submit an issue first to make sure it would be something that would be approved first :)

**Comment by Brian-McBride** [comment]
I think a flag would keep backward compat for a while.

**Comment by Brian-McBride** [comment]
I'll pull in a PR, no problem
