### ISSUE TITLE
[zod-mock] `min` not being respected with string regex

### ISSUE THREAD

**Issue by jonlaing** [anatine/zod-plugins#65]
I was seeing this in my own tests where I had a username schema which required a minimum length, but the mock fairly regularly doesn't respect that which is making my tests fragile:

```typescript
export const Username = z
  .string()
  .min(4)
  .max(32)
  .regex(/([\w\d_.]+$)/);
```

It seems like the lines that handle regex doesn't look at `min`:

```typescript
function parseString(
  zodRef: z.ZodString,
  options?: GenerateMockOptions
): string | number | boolean {
  // ...
  const regexCheck = checks.find((check) => check.kind === 'regex');
  if (regexCheck && 'regex' in regexCheck) {
    const generator = new randExp(regexCheck.regex);
    const max = checks.find((check) => check.kind === 'max');
    if (max && 'value' in max && typeof max.value === 'number') {
      generator.max = max.value;
    }
    const genRegString = generator.gen();
    return genRegString;
  }
  // ...
}
```
https://github.com/anatine/zod-plugins/blob/main/packages/zod-mock/src/lib/zod-mock.ts#L122

Not sure if this is intentional. I guess I could add the length check in the regex, but I thought I would point it out in case it was an oversight.

**Comment by Brian-McBride** [comment]
It is currently using the lib [`randexp`](https://www.npmjs.com/package/randexp)

It doesn't support a min value. Slicing the string up could result in some undesirable effects as well. 
For testing, while it is not ideal, you could drop in your own function:

```typescript
const schema = z.object({
  username: z.string().min(4).max(32).regex(/([\w\d_.]+$)/),
});

const mockData = generateMock(schema, {
  stringMap: {
    username: () => faker.helpers.arrayElement( ['cat',  'dog',  'mouse'] ),
  },
});
```

It isn't as ideal, but if you wanted to test with a few random strings that fit your regex properly.
