### ISSUE TITLE
Question: multipart/form-data with zod-openapi

### ISSUE THREAD

**Issue by seenark** [anatine/zod-plugins#69]
is there any way to upload image with binary via form-data
something like this 
`export class ProfileImage {
  @ApiProperty({ type: "string", format: "binary" })
  image: string;
}`
![image](https://user-images.githubusercontent.com/20698771/201623806-008fd899-5f72-4ec5-a02b-9435ba555932.png)

**Comment by Brian-McBride** [comment]
We are parsing Zod. 

You might be able to do it by extending the schema. 
```typescript
import { extendApi, generateSchema } from '@anatine/zod-openapi';
    
const profileBinarySchema = extendApi(z.string(), {
  format: 'binary',
});

export class ProfileImage extends createZodDto(profileBinarySchema) {}
```

That should work just fine.
