### ISSUE TITLE
Release workflow failed

### ISSUE THREAD

**Issue by trs** [anatine/zod-plugins#85]
Looks like one of the [last release workflows](https://github.com/anatine/zod-plugins/actions/runs/3818812885/jobs/6495946286) failed and did not end up releasing `zod-nestjs`

```
npm ERR!
 enoent ENOENT: no such file or directory, open '/home/runner/work/zod-plugins/zod-plugins/dist/packages/zod-nestjs/package.json'
```

It seems it's failing to compile? Or just has the wrong path set?

**Comment by Brian-McBride** [comment]
Hopefully fixed now
